# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âžœ"
# [character]                         # The name of the module we are configuring is "character"
# success_symbol = "[âžœ](bold green)"  # The "success_symbol" is set to "âžœ" with color "bold green"

# Use custom format
# format = """
# [â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
# [â”‚](bold green)$directory$rust$package
# [â””â”€>](bold green) """

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

#[hostname]
#ssh_only = false
#style = "bold dimmed white"
#disabled = false

#[username]
#style_user = "bold dimmed blue"
#show_always = true

#[time]
#disabled = false
#style = "bright-white"
#time_format = "ðŸ•™ %T"
